### ISSUE TITLE
Create Dashboard page for v2

### ISSUE THREAD

**Issue by dudesahn** [iearn-finance/yearn-finance#102]
**Is your feature request related to a problem? Please describe.**
v1 of the website has a nice dashboard page that serves as an overview of a user's positions [here](https://v1.yearn.finance/dashboard).

**Describe the solution you'd like**
Create a dashboard page for Yearn v2 UI. This should show an overview of the user's position up at the top with total holdings and interest earned. This page will also be very useful for users on mobile to check their positions.

**Describe alternatives you've considered**
N/A, we need this.

**Additional context**
WrongNebula created a mockup for what this dashboard page could look like below. This dashboard page would also link out to the various stats pages, which are featured in issue #103. Eventually, this dashboard could display a user's CREAM and Cover positions as well.

![image](https://user-images.githubusercontent.com/23222916/106402838-3016c980-63f1-11eb-9afd-2f24ee6067a4.png)

**Comment by self-coding-crab** [comment]
---

**Comment by dudesahn** [comment]
Moving forward with v3, not one of the major fixes included for v2.
