### ISSUE TITLE
Display Boost level for all Curve vaults

### ISSUE THREAD

**Issue by dudesahn** [iearn-finance/yearn-finance#126]
**Is your feature request related to a problem? Please describe.**
Users would be happy to know how boosted their yield is on Curve vaults, and Yearn's comparative yield compared to other protocols.

**Describe the solution you'd like**
Display Boost level for all Curve vaults on vaults UI.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by x48-crypto** [comment]
This has been implemented
