### ISSUE TITLE
Navigating to https://yearn.finance/cover is broken

### ISSUE THREAD

**Issue by dudesahn** [iearn-finance/yearn-finance#161]
## Description

Navigating to https://yearn.finance/cover, either directly or clicking through the navigation, is broken and brings up a blank, white screen. Briefly, yearn page shows up but then changes to white.

## Steps to reproduce

Navigate to https://yearn.finance/cover, either directly or clicking through the navigation.

**Expected behavior**
Cover page should show up.

**Screenshots**
![Screen Shot 2021-02-10 at 10 56 35 AM](https://user-images.githubusercontent.com/23222916/107535345-a7392400-6b8e-11eb-8e2d-a6bb65112d3d.png)
![Screen Shot 2021-02-10 at 10 56 46 AM](https://user-images.githubusercontent.com/23222916/107535379-adc79b80-6b8e-11eb-951b-5e113767a15f.png)

## Versions

- Browser: Brave
- yearn-finance:
- Node/NPM:

**Comment by jperl** [comment]
I'd be happy to help set up some e2e tests with [qawolf](https://www.qawolf.com) if you'd like. We integrate nicely with Vercel deployments.

**Comment by x48-crypto** [comment]
This is resolved now
