### ISSUE TITLE
Add ability to link to a vault

### ISSUE THREAD

**Issue by x48-crypto** [iearn-finance/yearn-finance#183]
Bounty: $200

Currently there is no way to link to a vault.

When a user clicks to expand a vault the following should happen
- Open vault accordion (this happens today)
- Change the route to https://yearn.finance/vaults/<vaultAddress>

When a user clicks to close a vault (and the user has not selected another vault) the following should happen:
- Close vault accordion (this happens today)
- Change the route to https://yearn.finance/vaults

When a user visits https://yearn.finance/vaults/<vaultAddress> the following should happen:
- Open the selected vault
- Scroll to the selected vault using a CSS animation using an anchor tag or similar

**Comment by wirjo** [comment]
Happy to try and tackle this in 8 hours or so if no one picks it up. I presume the URL can be `https://yearn.finance/vaults/<vault.address>`
