### ISSUE TITLE
Navigating directly to subdomains of v1.yearn.finance produces error

### ISSUE THREAD

**Issue by dudesahn** [iearn-finance/yearn-finance#48]
Navigating directly to any subdomain of `v1.yearn.finance` such as `v1.yearn.finance/lending`, `v1.yearn.finance/stats`, etc. shows the following error message below, but clicking through homepage `v1.yearn.finance` is fine.

![Wr4snYD](https://user-images.githubusercontent.com/23222916/105063455-c1795980-5a49-11eb-9759-716d310edfd6.png)

**Comment by nymmrx** [comment]
Resolved. Cloudfront configuration error + react-router.
