### ISSUE TITLE
Wallet Connect not working

### ISSUE THREAD

**Issue by dmolina79** [iearn-finance/yearn-finance#52]
## Description
Wallet Connect not working on mobile IOS, can't confirm if this happens on Android as well. Also confirmed is not working on Brave Desktop and have reports from other browsers

## Steps to reproduce

Connect to site using Iphone or IOS device and click <Launch App>. Wallet selection menu select <Wallet Connect>,
the menu stays up. Tested with other wallet connect enabled sites and they work as expected and show the prompt for wallet selection.

Stuck in this screen
![photo4915895047765993891](https://user-images.githubusercontent.com/6074987/105080414-6863f280-5a56-11eb-97de-34457e301864.jpg)

**Expected behavior**
Menu should close and open wallet selection screen from block native for approval.

**Screenshots**
![photo4915895047765993891](https://user-images.githubusercontent.com/6074987/105080414-6863f280-5a56-11eb-97de-34457e301864.jpg)

## Versions
v2 site Jan 19 2021
- React-Boilerplate:
- Node/NPM:
- Browser:

**Comment by dudesahn** [comment]
Received a report from a user that this is also broken on v1.yearn.finance for them as well, trying to connect iOS Trust Wallet to website
