### ISSUE TITLE
Error on loading v1 Lending UI; unusable

### ISSUE THREAD

**Issue by dudesahn** [iearn-finance/yearn-finance#59]
## Description
When users navigate to v1.yearn.finance/lending, receive the following error:
`Error: [BigNumber Error] Argument not a primitive number: 18` 
- Showing up for v1 lending, Supply and borrow balance showing $0 for users. I've confirmed this myself.
- Likely need `.toFixed(0)`  on a `BigNumber` somewhere according to Graham and x48

![](https://i.imgur.com/qqPhQxF.png)

Graham have looked into this and the cause is we are passing decimals variable to toFixed but decimals is sometimes a string whereas toFixed wants a number.  The following change fixes this (see line 4441 of stores/store.jsx), but then there are further errors that he didn't have time to investigate currently.

![](https://i.imgur.com/3lLA0ye.png)

Further errors to investigate after fixing decimals issue:

![](https://i.imgur.com/ulcqALI.png)

**Comment by x48-crypto** [comment]
resolved
