### ISSUE TITLE
Total Assets show "-" with Argent wallet connected on v2 vaults page

### ISSUE THREAD

**Issue by dudesahn** [iearn-finance/yearn-finance#70]
## Description

When using WalletConnect (Argent/iOS with Brave/MacOS), wallet connects successfully but does not seem to pull any data; TOTAL ASSETS remains only with a "–".

## Steps to reproduce

- Connect to yearn.finance/vaults using WalletConnect via Argent

**Expected behavior**
The vaults page should display total assets held in each vault, and this works correctly for me when I use MetaMask in the same browser.

**Screenshots**
![Screen Shot 2021-01-20 at 11 12 05 PM](https://user-images.githubusercontent.com/23222916/105279449-8a07cb80-5b75-11eb-834f-8b81b428b03a.png)

## Versions

- React-Boilerplate:
- Node/NPM:
- Browser: Brave 1.18.78

**Comment by x48-crypto** [comment]
Resolved
