### ISSUE TITLE
Fix vault re-render “ticking”

### ISSUE THREAD

**Issue by dudesahn** [iearn-finance/yearn-finance#95]
## Description

Vaults screen at yearn.finance/vaults seems to cycle and flashes briefly consistently.

## Steps to reproduce

Head to yearn.finance/vaults. No need to connect wallet, ticking occurs with or without connecting wallet. Interacting with vault list seems to trigger it as well.

**Expected behavior**
Vault screen and assets should not "tick".

**Screenshots**
N/A, hard to capture brief tick.

## Versions

- React-Boilerplate:
- Node/NPM:
- Browser: Brave

**Comment by shuffledex** [comment]
Fixed https://github.com/iearn-finance/yearn-finance/pull/92
